<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="CSPLAP0137" name="com.inquiry.tests.Report_VerifyTest" tests="8" failures="3" timestamp="13 Nov 2018 09:36:41 GMT" time="11.780" errors="0">
  <testcase name="headerInformation_FieldTest" time="0.548" classname="com.inquiry.tests.Report_VerifyTest"/>
  <testcase name="headerInformation_Field_ValueTest" time="0.577" classname="com.inquiry.tests.Report_VerifyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	issue date are not matched expected [13-11-2018] but found [15-10-2018],
	request date not matched expected [13-11-2018] but found [15-10-2018],
	report id not matched expected [TEST181113CR256614075] but found [TEST181015CR241084568]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	issue date are not matched expected [13-11-2018] but found [15-10-2018],
	request date not matched expected [13-11-2018] but found [15-10-2018],
	report id not matched expected [TEST181113CR256614075] but found [TEST181015CR241084568]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.inquiry.tests.Report_VerifyTest.headerInformation_Field_ValueTest(Report_VerifyTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- headerInformation_Field_ValueTest -->
  <testcase name="inquiryInputInfromationfield" time="0.000" classname="com.inquiry.tests.Report_VerifyTest">
    <skipped/>
  </testcase> <!-- inquiryInputInfromationfield -->
  <testcase name="inquiryInputInfromationValue" time="0.624" classname="com.inquiry.tests.Report_VerifyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Address Values are not Matching expected [FLAT NO.404 BLOCK C MAHAVEER REGAL HOODI BANGALORE  560066 KA] but found [FLAT NO.404 BLOCK C MAHAVEER REGAL HOODI BANGALORELORE 560066 KA]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Address Values are not Matching expected [FLAT NO.404 BLOCK C MAHAVEER REGAL HOODI BANGALORE  560066 KA] but found [FLAT NO.404 BLOCK C MAHAVEER REGAL HOODI BANGALORELORE 560066 KA]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.inquiry.tests.Report_VerifyTest.inquiryInputInfromationValue(Report_VerifyTest.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- inquiryInputInfromationValue -->
  <testcase name="testSummary_Section" time="2.101" classname="com.inquiry.tests.Report_VerifyTest"/>
  <testcase name="test_MemmberAccountInformation" time="2.369" classname="com.inquiry.tests.Report_VerifyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Realtionship_Field field is not matching. expected [Relationship #1] but found []">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Realtionship_Field field is not matching. expected [Relationship #1] but found []
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.inquiry.tests.Report_VerifyTest.test_MemmberAccountInformation(Report_VerifyTest.java:305)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- test_MemmberAccountInformation -->
  <testcase name="test_MemmberAccountInformationTradeLineField" time="5.220" classname="com.inquiry.tests.Report_VerifyTest"/>
  <testcase name="test_DisclaimerPresence" time="0.341" classname="com.inquiry.tests.Report_VerifyTest"/>
</testsuite> <!-- com.inquiry.tests.Report_VerifyTest -->
